defaults:
  - model: efficientnetb5_soft
  - data: document_onehot
  - train: default
  - wandb: wandb

project_name: document-classification
seed: 42

# hydra:
#   run:
#     dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
#   job:
#     chdir: False